### ISSUE TITLE
.fit attribute

### ISSUE THREAD

**Issue by sethubhargavmeruga** [adelekuzmiakova/CS229#1]
there is some issue with .fit attribute. when the code runs , the terminal returns 'function' has no attribute ' fit'.

**Comment by adele-k02** [comment]
Hi sethubhargavmeruga, 

Many thanks for raising this issue! Can you please tell me which code you're running? That would help me identify what the problem might be. Thanks again :-)   -Adele

**Comment by adele-k02** [comment]
Please see https://github.com/ColasGael/Machine-Learning-for-Solar-Energy-Prediction/issues/3 
We are fixing the bugs. Thank you :)
